### ISSUE TITLE
FLAC support?

### ISSUE THREAD

**Issue by Red6785** [Flazhik/CybergrindMusicExplorer#15]
:3

**Comment by Flazhik** [comment]
There's a couple of problems here.
Unfortunately, FLAC format isn't supported by Unity engine, hence couldn't be handled by CGME.
The only thing I could think of here is a potential feature which allows to decompress .flac to .wav in order to save the quality, but:
1. Such a conversion is a time consuming process and couldn't be done seamlessly
2. Unity will automatically resample any audio to 44kHz anyways

In any case, it wouldn't be a flac support per se and it's currently impossible.
